name: .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  patcher-tests:
    name: Run Cosmos.Patcher.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 9.0.x ]
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 🔄 Restore Dependencies
        run: dotnet restore ./tests/Cosmos.Patcher.Tests/Cosmos.Patcher.Tests.csproj

      - name: 🔨 Build Cosmos.Patcher
        run: dotnet build ./src/Cosmos.Patcher/Cosmos.Patcher.csproj

      - name: 🔨 Build Cosmos.Build.Patcher
        run: dotnet build ./src/Cosmos.Build.Patcher/Cosmos.Build.Patcher.csproj

      - name: 🔨 Build Cosmos.Patcher.Tests
        run: dotnet build ./tests/Cosmos.Patcher.Tests/Cosmos.Patcher.Tests.csproj --configuration Debug --no-restore

      - name: 🚀 Run Tests
        run: dotnet test ./tests/Cosmos.Patcher.Tests/Cosmos.Patcher.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Cosmos.Patcher.Tests.trx"

      - name: 📤 Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Cosmos.Patcher.Tests-Results
          path: ./tests/Cosmos.Patcher.Tests/TestResults/Cosmos.Patcher.Tests.trx

  scanner-tests:
    name: Run Cosmos.Scanner.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 9.0.x ]
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 🔄 Restore Dependencies
        run: dotnet restore ./tests/Cosmos.Scanner.Tests/Cosmos.Scanner.Tests.csproj

      - name: 🔨 Build Cosmos.Patcher
        run: dotnet build ./src/Cosmos.Patcher/Cosmos.Patcher.csproj

      - name: 🔨 Build Cosmos.Build.Patcher
        run: dotnet build ./src/Cosmos.Build.Patcher/Cosmos.Build.Patcher.csproj

      - name: 🔨 Build Cosmos.Scanner.Tests
        run: dotnet build ./tests/Cosmos.Scanner.Tests/Cosmos.Scanner.Tests.csproj --configuration Debug --no-restore

      - name: 🚀 Run Tests
        run: dotnet test ./tests/Cosmos.Scanner.Tests/Cosmos.Scanner.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Cosmos.Scanner.Tests.trx"

      - name: 📤 Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Cosmos.Scanner.Tests-Results
          path: ./tests/Cosmos.Scanner.Tests/TestResults/Cosmos.Scanner.Tests.trx

  analyzer-tests:
    name: Run Cosmos.Build.Analyzer.Patcher.Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 9.0.x ]
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 🔄 Restore Dependencies
        run: dotnet restore ./tests/Cosmos.Build.Analyzer.Patcher.Tests/Cosmos.Build.Analyzer.Patcher.Tests.csproj

      - name: 🔨 Build Cosmos.Patcher.Analyzer.Tests
        run: dotnet build ./tests/Cosmos.Build.Analyzer.Patcher.Tests/Cosmos.Build.Analyzer.Patcher.Tests.csproj --configuration Debug --no-restore

      - name: 🚀 Run Tests
        run: dotnet test ./tests/Cosmos.Build.Analyzer.Patcher.Tests/Cosmos.Build.Analyzer.Patcher.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Cosmos.Build.Analyzer.Patcher.Tests.trx"

      - name: 📤 Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Cosmos.Build.Analyzer.Patcher.Tests-Results
          path: ./tests/Cosmos.Build.Analyzer.Patcher.Tests/TestResults/Cosmos.Build.Analyzer.Patcher.Tests.trx

  asm-tests:
    name: Run Cosmos.Build.Asm.Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 9.0.x ]
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 🔗 Install Linking Tools
        run: sudo apt-get update && sudo apt-get install -y yasm

      - name: 🔄 Restore Dependencies
        run: dotnet restore ./tests/Cosmos.Build.Asm.Tests/Cosmos.Build.Asm.Tests.csproj

      - name: 🔨 Build Cosmos.Patcher
        run: dotnet build ./src/Cosmos.Patcher/Cosmos.Patcher.csproj

      - name: 🔨 Build Cosmos.Build.Patcher
        run: dotnet build ./src/Cosmos.Build.Patcher/Cosmos.Build.Patcher.csproj

      - name: 🔨 Build Cosmos.Build.Asm.Test
        run: dotnet build ./tests/Cosmos.Build.Asm.Tests/Cosmos.Build.Asm.Tests.csproj --configuration Debug --no-restore

      - name: 🚀 Run Tests
        run: dotnet test ./tests/Cosmos.Build.Asm.Tests/Cosmos.Build.Asm.Tests.csproj --no-build --configuration Debug --logger "trx;LogFileName=Cosmos.Build.Asm.Tests.trx"

      - name: 📤 Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Cosmos.Build.Asm.Test-Results
          path: ./tests/Cosmos.Build.Asm.Tests/TestResults/Cosmos.Build.Asm.Tests.trx

  unix-iso-tests:
    name: Run ISO Build Tests - Unix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 9.0.x ]
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: 🔄 Compile Packages
        run: ./.devcontainer/postCreateCommand.sh

      - name: 🔗 Install Linking Tools
        run: sudo apt-get update && sudo apt-get install -y xorriso lld yasm

      - name: 🔧 Install ilc
        run: dotnet tool install -g ilc

      - name: 🔧 Install Patcher
        run: dotnet tool install -g Cosmos.Patcher

      - name: 🔄 Restore Dependencies
        run: dotnet restore

      - name: 🚀 Run Tests
        run: dotnet publish -c Debug -r linux-x64 --verbosity detailed ./examples/KernelExample/Kernel.csproj -o ./output

      - name: 🕵️‍♂️ Verify Output
        run: |
          [ -f ./output/Kernel.iso ] && echo "ISO exists" || (echo "ISO missing" && exit 1)
